### ISSUE TITLE
`논의` Markdown css 관리 방법

### ISSUE THREAD

**Issue by YunKukPark** [CVLOG-project/CVL-frontend#11]
1. module로 관리
  - 장점 : module로 관리하기 때문에 불필요한 sass dependencies를 지워도 ㅇㅋ 
  - 단점 : 필요 시 마다 module import 필요
2. scss일반 파일로 관리
  - 장점 : 쉬움
  - 단점 : 불필요한 sass dependencies가 생김.

**Comment by gwanhun1** [comment]
현업에서 많이 쓰이는 방식을 따라가고 싶습니다.

**Comment by YunKukPark** [comment]
@gwanhun1  둘다 많이 쓰는 방식이라... 더군다나 tailwind를 사용하고 있는데 sass가 굳이 필요가 있을까.. 하는 생각이 들어서 올렸습니다.

sass module을 가장 많이 쓰는 것 같긴 해요.

**Comment by gwanhun1** [comment]
@YunKukPark  글면 저는 도전하겠습니다 모듈에 한표

**Comment by YunKukPark** [comment]
아 제가 위에 쓴 module은 그냥 css의 모듈입니다!
sass module이 아님!! 

css module은 많이 사용되고 있는지는 모르겠어요 저도 css module은 한번도 다뤄보진 않았습니다!
